import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import { Poppins } from "next/font/google";
import BotennicaChatbot from "@/temp";
const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  applicationName: "super bot",
  title: "super bot ",
  description: "Generated by super bot",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <QuaryClient >
          <Toaster position="top-right"
            reverseOrder={false} />
          <div className=" relative w-full min-h-screen ">
            {children}
          </div>

          <BotennicaChatbot />
        </QuaryClient>

        <script
            src="https://super-bot-x.vercel.app/widget.js"
            data-site-id="fdcsewrfdweefrd"
            defer
          ></script>

          {/* <script src="http://127.0.0.1:3000/widget.js" defer></script> */}
<script src="http://localhost:3000/widget.js" defer></script>


{/* <script
  src="https://super-bot-x.vercel.app/widget.js"
  data-site-id="my-awesome-react-site"
  defer
></script> */}


      </body>
    </html>
  );
}
