import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/provider/QuaryClient";
import { Poppins } from "next/font/google";
import BotennicaChatbot from "@/temp";
const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  applicationName: "superbot X",
  title: "superbot X",
  description: "Generated by superbot X",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <QuaryClient >
          <Toaster position="top-right"
            reverseOrder={false} />
          <div className=" relative w-full min-h-screen ">
            {children}
          </div>
          <BotennicaChatbot />
        </QuaryClient>

        <script
          id="superbot-widget"
          src="https://localhost:3000/widget.js"
          data-site-id="Vishal B_web_collection1762177514021"
          data-unique-id="cmhj6zy0j0001t0jaou1tgoz5"
          data-welcome-message="Hello! How can I assist you today?"
        ></script>

      </body>
    </html>
  );
}
